USE treinamento_capgemini;
CREATE TABLE VENDAS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATAVENDA DATE NOT NULL,
    CLIENTEID INT NOT NULL,
    TOTALVENDA FLOAT NOT NULL,
    FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES (ID)
);

CREATE TABLE ITENS_VENDAS(
    IDPRODUTO INT NOT NULL ,
    IDVENDA INT NOT NULL,
    VALORPRODUTO FLOAT NOT NULL,
    DESCONTO FLOAT NOT NULL,
    FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTOS (ID),
    FOREIGN KEY (IDVENDA) REFERENCES VENDAS (ID),
    PRIMARY KEY (IDPRODUTO, IDVENDA)
);

INSERT INTO PRODUTOS (DESCRICAO, QTDESTOQUE, PRECO, CATEGORIAID)
VALUES ('Presunto', 1000, 9, 2);

INSERT INTO VENDAS (DATAVENDA, CLIENTEID, TOTALVENDA)
VALUES ('2018-9-9', 1, 100);

INSERT INTO ITENS_VENDAS (IDPRODUTO, IDVENDA, VALORPRODUTO, DESCONTO)
VALUES (3, 1, 5, 10);



