USE treinamento_capgemini;

SELECT P.ID AS 'CODIGO', P.DESCRICAO, (P.PRECO * P.QTDESTOQUE) AS 'TOTAL', C.NOME AS 'CATEGORIA'
FROM PRODUTOS AS P INNER JOIN CATEGORIAS AS C ON P.CATEGORIAID = C.ID;

SELECT IDPRODUTO, (VALORPRODUTO - (VALORPRODUTO * DESCONTO/100))
FROM ITENS_VENDAS;