USE treinamento_capgemini;

SELECT COUNT(P.ID) AS 'QUANTIDADE', C.NOME
FROM PRODUTOS P INNER JOIN CATEGORIAS C on P.CATEGORIAID = C.ID
GROUP BY P.CATEGORIAID;

SELECT * FROM PRODUTOS ORDER BY PRECO;

SELECT * FROM PRODUTOS ORDER BY PRECO DESC;
